### ISSUE TITLE
Implement Resolution Scaling

### ISSUE THREAD

**Issue by jimen7** [jimen7/Hazard-Dash#7]
Look at the following tutorial and implement it https://edinburgh-napier.github.io/set09121/resolution.html

**Comment by GrowlingM1ke** [comment]
Managed to complete by changing engine.h and engine.cpp to include in the load of scene the maintain the game world when setting different resolutions. From now onwards the all physics and elements have to be dependent on GAMEX and GAMEY global variable instead of Engine::GetScreenSize(). Will create a new issue for that to change the current code.
